### ISSUE TITLE
As a user, when I navigate to the homepage, I will select the concert venue where I would like to book a seat.

### ISSUE THREAD

**Issue by kesamercy** [kesamercy/concert-seat-assignment#1]
**Tasks:**
- [x] Create 3 JSON files with different venue layouts to support the 3 different options for venues the user can choose from.
- [x] Create 3 buttons, each affiliated with a venue layout that a user can select.
- [x] Route the user to the venue layout page for the button they selected.

**Acceptance Tests:**
1. When the user arrives at the home page, they can see 3 buttons with different venue names to choose from.
2. When the user selects a button, they will be routed to the respective page. i.e if they selected button A, they have to be routed to the page for venue A.
