### ISSUE TITLE
Create 3 JSON files with different venue layouts to support the 3 different options for venues the user can choose from.

### ISSUE THREAD

**Issue by kesamercy** [kesamercy/concert-seat-assignment#2]
**Tasks:**
- [x] Create JSON file layout for madison, Kenedy center and Crisscross venue
- [x] Parse the JSON file input using php.

**Tests:**
 - [x] Json file input matches the parsed information
