### ISSUE TITLE
Code update, optmization and Update Testing files

### ISSUE THREAD

**Issue by kesamercy** [kesamercy/concert-seat-assignment#20]
##Tasks:##
- [x] modify single, double and tripple seat assignment code implementation. Aim to optimize the code.
- [x] add acceptance tests for the application 
- [x] Update read-me with program description
