### ISSUE TITLE
 Route the user to the venue layout page for the button they selected.

### ISSUE THREAD

**Issue by kesamercy** [kesamercy/concert-seat-assignment#4]
**Tasks:**
- [x] Change the buttons to form input. 
- [x] when the form is submitted, parse the json file based on the form name.
- [x] route the user to the venue page showing contents for the selected venue 

**Acceptance tests**
 - [x] when i click on a venue buttons I should be routed to a page where i see welcome message for that venue and the content for the respective venue
