### ISSUE TITLE
As a user, when I select the venue on the home page, I want to be redirected to the venue page where I can book a single seat

### ISSUE THREAD

**Issue by kesamercy** [kesamercy/concert-seat-assignment#5]
**Tasks:**

- [x] create a theatre layout based on the number of rows and columns for the stadium
- [x] show the user the seats available
- [x] create an option for the user to select a single seat assignment 

**Acceptance tests:**
