### ISSUE TITLE
create a theatre layout based on the number of rows and columns for each venue

### ISSUE THREAD

**Issue by kesamercy** [kesamercy/concert-seat-assignment#6]
**Tasks:**

- [x] get the number of rows and cols from the json file input 
- [x] use the rows and cols to draw the concert seat layout in php

**Acceptance Tests:**
- [x] when the user navigates to the venue page, they are able to see the venue layout with the rows and cols and number of seats available in each row
