### ISSUE TITLE
 show the user the seats available based on the json input

### ISSUE THREAD

**Issue by kesamercy** [kesamercy/concert-seat-assignment#9]
**Tasks:**

- [x] get all the seat numbers for all the seats available
- [x] affiliate the letter for each row with a number.
- [x] get the col number for each seat available
- [x] for each corresponding row and col, place an image of an empty seat

**Acceptance tests:**

- [x] when the user navigates to the venue page, they are able to see the seats available and those not available based on the empty seat images and the ones which are filled.
